//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyonOnline.ServiceReference.AdquirenciaV2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAuthorizedCredit", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class GetAuthorizedCredit : object
    {
        
        private string AnoField;
        
        private string CavvField;
        
        private string CepField;
        
        private string ComplementoField;
        
        private string CpfField;
        
        private string Cvc2Field;
        
        private string DistribuidorField;
        
        private string EciField;
        
        private string EnderecoField;
        
        private string FiliacaoField;
        
        private string IataField;
        
        private string IdentificacaoFaturaField;
        
        private string MesField;
        
        private string NrcartaoField;
        
        private string NumPedidoField;
        
        private string NumeroField;
        
        private string OrigemField;
        
        private string ParcelasField;
        
        private string PortadorField;
        
        private string RecorrenteField;
        
        private string SenhaField;
        
        private string TaxaEmbarqueField;
        
        private string TotalField;
        
        private int TransacaoField;
        
        private string XidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ano
        {
            get
            {
                return this.AnoField;
            }
            set
            {
                this.AnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cavv
        {
            get
            {
                return this.CavvField;
            }
            set
            {
                this.CavvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep
        {
            get
            {
                return this.CepField;
            }
            set
            {
                this.CepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento
        {
            get
            {
                return this.ComplementoField;
            }
            set
            {
                this.ComplementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf
        {
            get
            {
                return this.CpfField;
            }
            set
            {
                this.CpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvc2
        {
            get
            {
                return this.Cvc2Field;
            }
            set
            {
                this.Cvc2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distribuidor
        {
            get
            {
                return this.DistribuidorField;
            }
            set
            {
                this.DistribuidorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eci
        {
            get
            {
                return this.EciField;
            }
            set
            {
                this.EciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                this.EnderecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filiacao
        {
            get
            {
                return this.FiliacaoField;
            }
            set
            {
                this.FiliacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iata
        {
            get
            {
                return this.IataField;
            }
            set
            {
                this.IataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacaoFatura
        {
            get
            {
                return this.IdentificacaoFaturaField;
            }
            set
            {
                this.IdentificacaoFaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes
        {
            get
            {
                return this.MesField;
            }
            set
            {
                this.MesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nrcartao
        {
            get
            {
                return this.NrcartaoField;
            }
            set
            {
                this.NrcartaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPedido
        {
            get
            {
                return this.NumPedidoField;
            }
            set
            {
                this.NumPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origem
        {
            get
            {
                return this.OrigemField;
            }
            set
            {
                this.OrigemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parcelas
        {
            get
            {
                return this.ParcelasField;
            }
            set
            {
                this.ParcelasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Portador
        {
            get
            {
                return this.PortadorField;
            }
            set
            {
                this.PortadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recorrente
        {
            get
            {
                return this.RecorrenteField;
            }
            set
            {
                this.RecorrenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxaEmbarque
        {
            get
            {
                return this.TaxaEmbarqueField;
            }
            set
            {
                this.TaxaEmbarqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Transacao
        {
            get
            {
                return this.TransacaoField;
            }
            set
            {
                this.TransacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xid
        {
            get
            {
                return this.XidField;
            }
            set
            {
                this.XidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditAuthorizationResponse", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class CreditAuthorizationResponse : object
    {
        
        private string CetField;
        
        private string CodRetField;
        
        private string DataField;
        
        private string HoraField;
        
        private string JurosField;
        
        private string MsgAvsField;
        
        private string MsgretField;
        
        private string NumAutorField;
        
        private string NumPedidoField;
        
        private string NumSqnField;
        
        private string RespAvsField;
        
        private string TidField;
        
        private string ValParcelasField;
        
        private string ValTotalJurosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cet
        {
            get
            {
                return this.CetField;
            }
            set
            {
                this.CetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                this.CodRetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Juros
        {
            get
            {
                return this.JurosField;
            }
            set
            {
                this.JurosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgAvs
        {
            get
            {
                return this.MsgAvsField;
            }
            set
            {
                this.MsgAvsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msgret
        {
            get
            {
                return this.MsgretField;
            }
            set
            {
                this.MsgretField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAutor
        {
            get
            {
                return this.NumAutorField;
            }
            set
            {
                this.NumAutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPedido
        {
            get
            {
                return this.NumPedidoField;
            }
            set
            {
                this.NumPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSqn
        {
            get
            {
                return this.NumSqnField;
            }
            set
            {
                this.NumSqnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespAvs
        {
            get
            {
                return this.RespAvsField;
            }
            set
            {
                this.RespAvsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid
        {
            get
            {
                return this.TidField;
            }
            set
            {
                this.TidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValParcelas
        {
            get
            {
                return this.ValParcelasField;
            }
            set
            {
                this.ValParcelasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValTotalJuros
        {
            get
            {
                return this.ValTotalJurosField;
            }
            set
            {
                this.ValTotalJurosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcecaoAmigavel", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class ExcecaoAmigavel : object
    {
        
        private string MensagemField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAuthorizedDebit", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class GetAuthorizedDebit : object
    {
        
        private string AnoField;
        
        private string CavvField;
        
        private string CepField;
        
        private string ComplementoField;
        
        private string CpfField;
        
        private string Cvc2Field;
        
        private string DistribuidorField;
        
        private string EciField;
        
        private string EnderecoField;
        
        private string FiliacaoField;
        
        private string IataField;
        
        private string IdentificacaoFaturaField;
        
        private string MesField;
        
        private string NrcartaoField;
        
        private string NumPedidoField;
        
        private string NumeroField;
        
        private string OrigemField;
        
        private string ParcelasField;
        
        private string PortadorField;
        
        private string SenhaField;
        
        private string TaxaEmbarqueField;
        
        private string TotalField;
        
        private int TransacaoField;
        
        private string XidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ano
        {
            get
            {
                return this.AnoField;
            }
            set
            {
                this.AnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cavv
        {
            get
            {
                return this.CavvField;
            }
            set
            {
                this.CavvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep
        {
            get
            {
                return this.CepField;
            }
            set
            {
                this.CepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento
        {
            get
            {
                return this.ComplementoField;
            }
            set
            {
                this.ComplementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf
        {
            get
            {
                return this.CpfField;
            }
            set
            {
                this.CpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvc2
        {
            get
            {
                return this.Cvc2Field;
            }
            set
            {
                this.Cvc2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distribuidor
        {
            get
            {
                return this.DistribuidorField;
            }
            set
            {
                this.DistribuidorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eci
        {
            get
            {
                return this.EciField;
            }
            set
            {
                this.EciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                this.EnderecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filiacao
        {
            get
            {
                return this.FiliacaoField;
            }
            set
            {
                this.FiliacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iata
        {
            get
            {
                return this.IataField;
            }
            set
            {
                this.IataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacaoFatura
        {
            get
            {
                return this.IdentificacaoFaturaField;
            }
            set
            {
                this.IdentificacaoFaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes
        {
            get
            {
                return this.MesField;
            }
            set
            {
                this.MesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nrcartao
        {
            get
            {
                return this.NrcartaoField;
            }
            set
            {
                this.NrcartaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPedido
        {
            get
            {
                return this.NumPedidoField;
            }
            set
            {
                this.NumPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origem
        {
            get
            {
                return this.OrigemField;
            }
            set
            {
                this.OrigemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parcelas
        {
            get
            {
                return this.ParcelasField;
            }
            set
            {
                this.ParcelasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Portador
        {
            get
            {
                return this.PortadorField;
            }
            set
            {
                this.PortadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxaEmbarque
        {
            get
            {
                return this.TaxaEmbarqueField;
            }
            set
            {
                this.TaxaEmbarqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Transacao
        {
            get
            {
                return this.TransacaoField;
            }
            set
            {
                this.TransacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xid
        {
            get
            {
                return this.XidField;
            }
            set
            {
                this.XidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authorization", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class Authorization : object
    {
        
        private string CodRetField;
        
        private string DataField;
        
        private string HoraField;
        
        private string MsgAvsField;
        
        private string MsgretField;
        
        private string NumAutorField;
        
        private string NumPedidoField;
        
        private string NumSqnField;
        
        private string RespAvsField;
        
        private string TidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                this.CodRetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgAvs
        {
            get
            {
                return this.MsgAvsField;
            }
            set
            {
                this.MsgAvsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msgret
        {
            get
            {
                return this.MsgretField;
            }
            set
            {
                this.MsgretField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAutor
        {
            get
            {
                return this.NumAutorField;
            }
            set
            {
                this.NumAutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPedido
        {
            get
            {
                return this.NumPedidoField;
            }
            set
            {
                this.NumPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSqn
        {
            get
            {
                return this.NumSqnField;
            }
            set
            {
                this.NumSqnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespAvs
        {
            get
            {
                return this.RespAvsField;
            }
            set
            {
                this.RespAvsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid
        {
            get
            {
                return this.TidField;
            }
            set
            {
                this.TidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoidTransactionTID", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class VoidTransactionTID : object
    {
        
        private string DataField;
        
        private string FiliacaoField;
        
        private string NumAutorField;
        
        private string NumSqnField;
        
        private string SenhaField;
        
        private string TidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filiacao
        {
            get
            {
                return this.FiliacaoField;
            }
            set
            {
                this.FiliacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAutor
        {
            get
            {
                return this.NumAutorField;
            }
            set
            {
                this.NumAutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSqn
        {
            get
            {
                return this.NumSqnField;
            }
            set
            {
                this.NumSqnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid
        {
            get
            {
                return this.TidField;
            }
            set
            {
                this.TidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Confirmation", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class Confirmation : object
    {
        
        private string CodRetField;
        
        private string DataField;
        
        private string HoraField;
        
        private string MsgRetField;
        
        private string NumSqnField;
        
        private string TidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                this.CodRetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgRet
        {
            get
            {
                return this.MsgRetField;
            }
            set
            {
                this.MsgRetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSqn
        {
            get
            {
                return this.NumSqnField;
            }
            set
            {
                this.NumSqnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid
        {
            get
            {
                return this.TidField;
            }
            set
            {
                this.TidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmTxnTID", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class ConfirmTxnTID : object
    {
        
        private string DataField;
        
        private string FiliacaoField;
        
        private string NumAutorField;
        
        private string NumSqnField;
        
        private string ParcelasField;
        
        private string SenhaField;
        
        private string TidField;
        
        private string TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filiacao
        {
            get
            {
                return this.FiliacaoField;
            }
            set
            {
                this.FiliacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAutor
        {
            get
            {
                return this.NumAutorField;
            }
            set
            {
                this.NumAutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSqn
        {
            get
            {
                return this.NumSqnField;
            }
            set
            {
                this.NumSqnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parcelas
        {
            get
            {
                return this.ParcelasField;
            }
            set
            {
                this.ParcelasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid
        {
            get
            {
                return this.TidField;
            }
            set
            {
                this.TidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryRequest", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class QueryRequest : object
    {
        
        private string FiliacaoField;
        
        private string NumPedidoField;
        
        private string SenhaField;
        
        private string TidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filiacao
        {
            get
            {
                return this.FiliacaoField;
            }
            set
            {
                this.FiliacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPedido
        {
            get
            {
                return this.NumPedidoField;
            }
            set
            {
                this.NumPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid
        {
            get
            {
                return this.TidField;
            }
            set
            {
                this.TidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResponse", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class QueryResponse : object
    {
        
        private SyonOnline.ServiceReference.AdquirenciaV2.HeaderClass HEADERField;
        
        private SyonOnline.ServiceReference.AdquirenciaV2.RegistroClass REGISTROField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyonOnline.ServiceReference.AdquirenciaV2.HeaderClass HEADER
        {
            get
            {
                return this.HEADERField;
            }
            set
            {
                this.HEADERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyonOnline.ServiceReference.AdquirenciaV2.RegistroClass REGISTRO
        {
            get
            {
                return this.REGISTROField;
            }
            set
            {
                this.REGISTROField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderClass", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class HeaderClass : object
    {
        
        private string DATA_REQUISICAOField;
        
        private string FILIACAOField;
        
        private string HORA_REQUISICAOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_REQUISICAO
        {
            get
            {
                return this.DATA_REQUISICAOField;
            }
            set
            {
                this.DATA_REQUISICAOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILIACAO
        {
            get
            {
                return this.FILIACAOField;
            }
            set
            {
                this.FILIACAOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HORA_REQUISICAO
        {
            get
            {
                return this.HORA_REQUISICAOField;
            }
            set
            {
                this.HORA_REQUISICAOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroClass", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class RegistroClass : object
    {
        
        private SyonOnline.ServiceReference.AdquirenciaV2.AvsQueryClass AVSField;
        
        private string COD_RETField;
        
        private string DATAField;
        
        private string DATA_CANCField;
        
        private string DATA_CON_PRE_AUTField;
        
        private string DATA_EXP_PRE_AUTField;
        
        private string FILIACAO_DSTRField;
        
        private string HORAField;
        
        private string IDENTIFICACAOFATURAField;
        
        private string MOEDAField;
        
        private string MSG_RETField;
        
        private string NOM_PORTADORField;
        
        private string NR_CARTAOField;
        
        private string NUMAUTORField;
        
        private string NUMPEDIDOField;
        
        private string NUMSQNField;
        
        private string ORIGEMField;
        
        private string PARCELASField;
        
        private string STATUSField;
        
        private string TAXA_EMBARQUEField;
        
        private string TIDField;
        
        private string TOTALField;
        
        private string TRANSACAOField;
        
        private SyonOnline.ServiceReference.AdquirenciaV2.ThreeDClass _3DSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyonOnline.ServiceReference.AdquirenciaV2.AvsQueryClass AVS
        {
            get
            {
                return this.AVSField;
            }
            set
            {
                this.AVSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_RET
        {
            get
            {
                return this.COD_RETField;
            }
            set
            {
                this.COD_RETField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA
        {
            get
            {
                return this.DATAField;
            }
            set
            {
                this.DATAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_CANC
        {
            get
            {
                return this.DATA_CANCField;
            }
            set
            {
                this.DATA_CANCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_CON_PRE_AUT
        {
            get
            {
                return this.DATA_CON_PRE_AUTField;
            }
            set
            {
                this.DATA_CON_PRE_AUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_EXP_PRE_AUT
        {
            get
            {
                return this.DATA_EXP_PRE_AUTField;
            }
            set
            {
                this.DATA_EXP_PRE_AUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FILIACAO_DSTR
        {
            get
            {
                return this.FILIACAO_DSTRField;
            }
            set
            {
                this.FILIACAO_DSTRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HORA
        {
            get
            {
                return this.HORAField;
            }
            set
            {
                this.HORAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDENTIFICACAOFATURA
        {
            get
            {
                return this.IDENTIFICACAOFATURAField;
            }
            set
            {
                this.IDENTIFICACAOFATURAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOEDA
        {
            get
            {
                return this.MOEDAField;
            }
            set
            {
                this.MOEDAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSG_RET
        {
            get
            {
                return this.MSG_RETField;
            }
            set
            {
                this.MSG_RETField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_PORTADOR
        {
            get
            {
                return this.NOM_PORTADORField;
            }
            set
            {
                this.NOM_PORTADORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NR_CARTAO
        {
            get
            {
                return this.NR_CARTAOField;
            }
            set
            {
                this.NR_CARTAOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMAUTOR
        {
            get
            {
                return this.NUMAUTORField;
            }
            set
            {
                this.NUMAUTORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMPEDIDO
        {
            get
            {
                return this.NUMPEDIDOField;
            }
            set
            {
                this.NUMPEDIDOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMSQN
        {
            get
            {
                return this.NUMSQNField;
            }
            set
            {
                this.NUMSQNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORIGEM
        {
            get
            {
                return this.ORIGEMField;
            }
            set
            {
                this.ORIGEMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARCELAS
        {
            get
            {
                return this.PARCELASField;
            }
            set
            {
                this.PARCELASField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS
        {
            get
            {
                return this.STATUSField;
            }
            set
            {
                this.STATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TAXA_EMBARQUE
        {
            get
            {
                return this.TAXA_EMBARQUEField;
            }
            set
            {
                this.TAXA_EMBARQUEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TID
        {
            get
            {
                return this.TIDField;
            }
            set
            {
                this.TIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOTAL
        {
            get
            {
                return this.TOTALField;
            }
            set
            {
                this.TOTALField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANSACAO
        {
            get
            {
                return this.TRANSACAOField;
            }
            set
            {
                this.TRANSACAOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="3DS")]
        public SyonOnline.ServiceReference.AdquirenciaV2.ThreeDClass _3DS
        {
            get
            {
                return this._3DSField;
            }
            set
            {
                this._3DSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvsQueryClass", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class AvsQueryClass : object
    {
        
        private string CEPField;
        
        private string COMPLEMENTOField;
        
        private string CPFField;
        
        private string ENDERECOField;
        
        private string MSG_AVSField;
        
        private string NU_ENDERECOField;
        
        private string RESP_AVSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP
        {
            get
            {
                return this.CEPField;
            }
            set
            {
                this.CEPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPLEMENTO
        {
            get
            {
                return this.COMPLEMENTOField;
            }
            set
            {
                this.COMPLEMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF
        {
            get
            {
                return this.CPFField;
            }
            set
            {
                this.CPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENDERECO
        {
            get
            {
                return this.ENDERECOField;
            }
            set
            {
                this.ENDERECOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSG_AVS
        {
            get
            {
                return this.MSG_AVSField;
            }
            set
            {
                this.MSG_AVSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NU_ENDERECO
        {
            get
            {
                return this.NU_ENDERECOField;
            }
            set
            {
                this.NU_ENDERECOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESP_AVS
        {
            get
            {
                return this.RESP_AVSField;
            }
            set
            {
                this.RESP_AVSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThreeDClass", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
    public partial class ThreeDClass : object
    {
        
        private string CAVVField;
        
        private string ECIField;
        
        private string XIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAVV
        {
            get
            {
                return this.CAVVField;
            }
            set
            {
                this.CAVVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECI
        {
            get
            {
                return this.ECIField;
            }
            set
            {
                this.ECIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XID
        {
            get
            {
                return this.XIDField;
            }
            set
            {
                this.XIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyonOnline.ServiceReference.AdquirenciaV2.IKomerciWcf")]
    public interface IKomerciWcf
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomerciWcf/GetAuthorizedCredit", ReplyAction="http://tempuri.org/IKomerciWcf/GetAuthorizedCreditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SyonOnline.ServiceReference.AdquirenciaV2.ExcecaoAmigavel), Action="http://tempuri.org/IKomerciWcf/GetAuthorizedCreditExcecaoAmigavelFault", Name="ExcecaoAmigavel", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
        System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.CreditAuthorizationResponse> GetAuthorizedCreditAsync(SyonOnline.ServiceReference.AdquirenciaV2.GetAuthorizedCredit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomerciWcf/GetAuthorizedDebit", ReplyAction="http://tempuri.org/IKomerciWcf/GetAuthorizedDebitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SyonOnline.ServiceReference.AdquirenciaV2.ExcecaoAmigavel), Action="http://tempuri.org/IKomerciWcf/GetAuthorizedDebitExcecaoAmigavelFault", Name="ExcecaoAmigavel", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
        System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.Authorization> GetAuthorizedDebitAsync(SyonOnline.ServiceReference.AdquirenciaV2.GetAuthorizedDebit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomerciWcf/VoidTransactionTID", ReplyAction="http://tempuri.org/IKomerciWcf/VoidTransactionTIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SyonOnline.ServiceReference.AdquirenciaV2.ExcecaoAmigavel), Action="http://tempuri.org/IKomerciWcf/VoidTransactionTIDExcecaoAmigavelFault", Name="ExcecaoAmigavel", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
        System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.Confirmation> VoidTransactionTIDAsync(SyonOnline.ServiceReference.AdquirenciaV2.VoidTransactionTID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomerciWcf/ConfirmTxnTID", ReplyAction="http://tempuri.org/IKomerciWcf/ConfirmTxnTIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SyonOnline.ServiceReference.AdquirenciaV2.ExcecaoAmigavel), Action="http://tempuri.org/IKomerciWcf/ConfirmTxnTIDExcecaoAmigavelFault", Name="ExcecaoAmigavel", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
        System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.Authorization> ConfirmTxnTIDAsync(SyonOnline.ServiceReference.AdquirenciaV2.ConfirmTxnTID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomerciWcf/Query", ReplyAction="http://tempuri.org/IKomerciWcf/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SyonOnline.ServiceReference.AdquirenciaV2.ExcecaoAmigavel), Action="http://tempuri.org/IKomerciWcf/QueryExcecaoAmigavelFault", Name="ExcecaoAmigavel", Namespace="http://schemas.datacontract.org/2004/07/Redecard.Komerci.External.WcfKomerci")]
        System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.QueryResponse> QueryAsync(SyonOnline.ServiceReference.AdquirenciaV2.QueryRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IKomerciWcfChannel : SyonOnline.ServiceReference.AdquirenciaV2.IKomerciWcf, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class KomerciWcfClient : System.ServiceModel.ClientBase<SyonOnline.ServiceReference.AdquirenciaV2.IKomerciWcf>, SyonOnline.ServiceReference.AdquirenciaV2.IKomerciWcf
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KomerciWcfClient() : 
                base(KomerciWcfClient.GetDefaultBinding(), KomerciWcfClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IKomerciWcf.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomerciWcfClient(EndpointConfiguration endpointConfiguration) : 
                base(KomerciWcfClient.GetBindingForEndpoint(endpointConfiguration), KomerciWcfClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomerciWcfClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KomerciWcfClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomerciWcfClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KomerciWcfClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomerciWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.CreditAuthorizationResponse> GetAuthorizedCreditAsync(SyonOnline.ServiceReference.AdquirenciaV2.GetAuthorizedCredit request)
        {
            return base.Channel.GetAuthorizedCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.Authorization> GetAuthorizedDebitAsync(SyonOnline.ServiceReference.AdquirenciaV2.GetAuthorizedDebit request)
        {
            return base.Channel.GetAuthorizedDebitAsync(request);
        }
        
        public System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.Confirmation> VoidTransactionTIDAsync(SyonOnline.ServiceReference.AdquirenciaV2.VoidTransactionTID request)
        {
            return base.Channel.VoidTransactionTIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.Authorization> ConfirmTxnTIDAsync(SyonOnline.ServiceReference.AdquirenciaV2.ConfirmTxnTID request)
        {
            return base.Channel.ConfirmTxnTIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SyonOnline.ServiceReference.AdquirenciaV2.QueryResponse> QueryAsync(SyonOnline.ServiceReference.AdquirenciaV2.QueryRequest request)
        {
            return base.Channel.QueryAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IKomerciWcf))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IKomerciWcf))
            {
                return new System.ServiceModel.EndpointAddress("https://ecommerce.userede.com.br/Redecard.Adquirencia.Wcf/KomerciWcfV2.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KomerciWcfClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IKomerciWcf);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KomerciWcfClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IKomerciWcf);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IKomerciWcf,
        }
    }
}
